### PR TITLE
Fix type-checker timeouts that break the build on Xcode 26.1

### PR DESCRIPTION
**Pull request by marcushorndt**
On Xcode 26.1 (Swift 6.2.1, macOS 26.1 SDK), a clean Release build of the `Compositor` scheme fails at 1.1.8 with:

```
Compositor/Document/ImageAdjustments.swift:91:13: error: the compiler is unable
to type-check this expression in reasonable time; ...
Compositor/ContentView.swift: error: the compiler is unable to type-check this
expression in reasonable time; try breaking up the expression into distinct
sub-expressions
```

These are solver timeouts, not real type errors. The build fails outright, and raising `-solver-expression-time-threshold` does not help.

**`ImageAdjustments.swift`**: the gradient map built its 768-entry lookup table in one nested `flatMap`/`map` over an array literal of mixed `Double` arithmetic. It now fills the table in explicitly typed steps, with the same values in the same order.

**`ContentView.swift`**: `body` combines nine tool-header branches, the layout and about twenty chained modifiers. It is split into `toolHeaders`, `editorStack` and `editorChrome`, and `body` keeps the change handlers, the file importer and the alerts. The view tree is unchanged. One split was enough at 1.0.4; 1.1 added enough modifiers that it needed a second one, which this update adds.

Both are mechanical rewrites: the same view tree and the same arithmetic. A before-and-after pixel diff is not possible, because the unpatched tree does not build on this toolchain. I confirmed that a gradient-map document still renders correctly through `ImageExporter` after the change.

### Verified at 1.1.8 (`c39da13`)

- `xcodebuild -scheme Compositor -configuration Release` succeeds
- The app launches, opens and saves projects, and renders correctly
- Xcode 26.1.1 (17B100), Swift 6.2.1, macOS 27.0

I'm happy to change the split if you would rather factor it differently.

---

Context: I hit these while building a small MCP server that drives Compositor documents headlessly ([compositor-mcp](https://github.com/marcushorndt/compositor-mcp)). Your separation of the document model from the UI made that unusually pleasant, so thank you for that.

### CODE REVIEW

**Comment by robbietilton** [comment]
Merged. You were right that this mattered more than it looked: by the time I took it, two other contributors had independently hit the same wall and were each carrying their own ContentView restructuring inside unrelated PRs. Landing this let me drop those and keep their diffs to the actual feature.

I checked the gradient map table across 2,443 endpoint pairs before merging — zero differing bytes, as you said. Thanks also for splitting it the way you did; toolHeaders and editorStack read better than what was there.
